package:
  name: spectacoular
  version: "20.11"

source:
  path: ../../spectacoular

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - acoular = acoular:main
    #
    # Would create an entry point called acoular that calls acoular.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - Acoular>=20.10
    - bokeh >=1.2.0


  run:
    - python >=3.8
    - Acoular>=20.10
    - bokeh >=1.2.0

test:
  # Python imports

  files: # from recipe folder
 #   - some file


  imports:
    - spectacoular

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.acoular.org
  license: BSD License
  summary: 'Library for acoustic beamforming'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
