package:
  name: spectacoular
  version: "{{ os.popen('hatch version').read().strip() }}"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps -vv .

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python >=3.10
    - acoular >=25.01
    - bokeh >=3.0
    - python-sounddevice

test:
  # Python imports

  files: # from recipe folder
 #   - some file

  imports:
    - spectacoular

about:
  home: https://acoular.github.io/spectacoular/
  license: BSD License
  summary: 'Library for SpectAcoular interactive applications with Acoular'

