{% set pyproject = load_file_data('../pyproject.toml',from_recipe_dir=True) %}
{% set version = pyproject['project']['version'] %}

package:
  name: spectacoular
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps -vv .

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python >=3.8
    - acoular >=24.05
    - bokeh >=3.0

# test:
#   # Python imports

#   files: # from recipe folder
#  #   - some file

#   imports:
#     - spectacoular

about:
  home: https://acoular.github.io/spectacoular/
  license: BSD License
  summary: 'Library for SpectAcoular interactive applications with Acoular'

