name: Build conda package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ "*" ]
    
jobs:
  conda_build_and_install:
    name: Test conda deployment of package with Python 3.12
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: ./.github/actions/setup-conda
      - name: Set up hatch
        uses: ./.github/actions/setup-hatch
      - name: Build package
        run: conda build --no-anaconda-upload --no-copy-test-source-files recipe.local --output-folder ./conda_package -c acoular -c conda-forge
      - name: Upload conda package artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-package
          path: ./conda_package

