name: "Manual: Docs 📝 Build 🛠️ & Deploy"
run-name: Build & Deploy SpectAcoular dev docs → acoular.org/spectacoular/dev
permissions:
  contents: read
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      artifact_name: build-docs-dev
      artifact_path: ./docs/_build/html
      html_baseurl: "https://acoular.org/spectacoular/dev/"
      docs_version_match: "dev"

  deploy:
    needs: build
    uses: acoular/ci/.github/workflows/package-docs-deploy.yml@main
    with:
      artifact_name: build-docs-dev
      artifact_path: ./docs/_build/html
      destination_dir: spectacoular/dev
      package_path: /spectacoular
      min_version: v26.06
      deploy_switcher: true
    secrets:
      website_gh_pages_token: ${{ secrets.WEBSITE_GH_PAGES_TOKEN }}
