name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13']
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v4
      - name: Set up hatch
        uses: ./.github/actions/setup-hatch
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up PortAudio
        uses: ./.github/actions/setup-portaudio
        with:
          os: ${{ matrix.os }}
      - name: Check import
        run: hatch -v run +py=${{ matrix.python-version }} tests:import
      - name: Run tests
        run: hatch -v run +py=${{ matrix.python-version }} tests:test
